#!/bin/bash

echo "// Recommends are as of now still abused in many packages
APT::Install-Recommends \"0\";
APT::Install-Suggests \"0\";

// Always keep stuff clean
Apt::Get::Clean-Installed \"true\";
Dselect::Clean \"always\";" | sudo tee /etc/apt/apt.conf

echo "# Debian Multimediadeb http://ftp.uni-kl.de/debian-multimedia/ unstable main 
deb-src http://ftp.uni-kl.de/debian-multimedia/ unstable main 

deb http://ftp.uni-kl.de/debian-multimedia/ testing main 
deb-src http://ftp.uni-kl.de/debian-multimedia/ testing main

# Official rPi
deb http://mirrordirector.raspbian.org jessie main contrib non-free
deb-src http://mirrordirector.raspbian.org jessie main contrib non-free

# Official OSMC
deb http://apt.osmc.tv jessie main
deb-src http://apt.osmc.tv jessie main

# Nanolx
deb http://apt.nanolx.org/ photonic main
deb-src http://apt.nanolx.org/ photonic main" | sudo tee /etc/apt/sources.list

sudo apt-get update
sudo apt-get -y --force-yes install deb-multimedia-keyring
wget -q http://www.nanolx.org/apt/photonic.asc -O nanolx.key
sudo apt-key add nanolx.key
rm nanolx.key
sudo apt-get update
