#!/bin/bash

cd ${HOME}

echo "choose what to download/install:

0	bcm2835			kernel module for c-berry
1	c-berry			official c-berry examples
2	c-berry-python		7soft c-berry python examples
3	c-berry-pthon-lib	pixelsetzer c-berry python lib
4	suld			samsung unified linux driver"

read userchoise

case ${userchoise} in
	0 | bcm2835 )
		wget http://www.airspayce.com/mikem/bcm2835/bcm2835-1.36.tar.gz
		tar xf bcm2835-1.36.tar.gz && cd bcm2835-1.36
		./configure && make && sudo make check && sudo make install
	;;

	1 | c-berry )
		wget http://admatec.de/sites/default/files/downloads/C-Berry.tar.gz
		tar xf C-Berry.tar.gz
	;;

	2 | c-berry-python )
		wget http://www.7soft.de/uploads/Software/C-Berry-python.tgz
		tar xf C-Berry-python.tgz
	;;

	3 | c-berry-python-lib )
		sudo apt-get install git python-dev
		git clone https://github.com/pixelsetzer/cbplib.git
		cd cbplib
		sudo python setup.py install
	;;

	4 | suld )
		sudo apt-get install cups cups-pdf cups-bsd
		sudo cupsctl --share-printers --remote-admin
		wget http://downloadcenter.samsung.com/content/DR/201308/20130802091941159/ULD_Linux_V1.00.06.tar.gz
		tar xf ULD_Linux_V1.00.06.tar.gz || exit 1
		cd uld/
		sed -e 's/= \"arm\"/= \"arm\" -o \"$ARCH\" = \"armv6l\"/' -i noarch/packet.sh
		sed -e '490,495d' -i noarch/packet.sh
		sudo ./install.sh
		sudo cp arm/* /usr/lib/cups/filter/
		sudo /etc/init.d/cups restart
	;;

	* )
		echo "invalid choice made."
		exit 1
	;;
esac
