#!/bin/bash

PI_ADDR=192.168.0.125
PI_PORT=1337
PI_USER=nano

for arg in "${@}"; do
	if [[ "${arg}" == */ ]]; then
			scp -P ${PI_PORT} -r ${PI_USER}@${PI_ADDR}:"${1}" "${PWD}"
	else
		scp -P ${PI_PORT} ${PI_USER}@${PI_ADDR}:"${1}" "${PWD}"
	fi
done
