#!/bin/bash

#PI_ADDR=192.168.0.125 #LAN
PI_ADDR=192.168.0.126 #WiFi

PI_PORT=1337
PI_USER=nano

for arg in "${@}"; do
	if [[ ! -e "${arg}" ]]; then
		echo "${arg} does not exist!"
	else
		if [[ -f "${arg}" ]]; then
			scp -P ${PI_PORT} "${arg}" ${PI_USER}@${PI_ADDR}:/home/${PI_USER}/
		elif [[ -d "${arg}" ]]; then
			scp -P ${PI_PORT} -r "${arg}" ${PI_USER}@${PI_ADDR}:/home/${PI_USER}/
		fi
	fi
done
