#!/bin/bash

sudo apt-get install cups cups-pdf cups-bsd
sudo cupsctl --share-printers --remote-admin 
wget http://downloadcenter.samsung.com/content/DR/201308/20130802091941159/ULD_Linux_V1.00.06.tar.gz
tar xf ULD_Linux_V1.00.06.tar.gz || exit 1
cd uld/
sed -e 's/= \"arm\"/= \"arm\" -o \"$ARCH\" = \"armv6l\"/' -i noarch/packet.sh
sed -e '490,495d' -i noarch/packet.sh
sudo ./install.sh
sudo cp arm/* /usr/lib/cups/filter/
sudo /etc/init.d/cups restart
