#!/bin/bash

echo "options 8192cu rtw_power_mgnt=0 rtw_enusbss=0" | \
	sudo tee /etc/modprobe.d/8192cu.conf

echo -e "\n\n *** enter WiFi SSID (Network Name) *** \n"
read WIFI_SSID

echo -e "\n\n *** enter WiFi Password *** \n"
read WIFI_PSK

echo "auto lo
iface lo inet loopback
iface eth0 inet dhcp

auto wlan0
allow-hotplug wlan0
iface wlan0 inet dhcp
wpa-ap-scan 1
wpa-scan-ssid 1
wpa-ssid "${WIFI_SSID}"
wpa-psk "${WIFI_PSK}" | \
	sudo tee /etc/network/interfaces

sudo service networking restart
