#!/bin/sh
### BEGIN INIT INFO
# Provides: xinit
# Required-Start: $remote_fs $syslog $bluetooth
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: custom stuff
# Description: bluetooth / display-stats
### END INIT INFO

INIT_DIRECTORY=/etc/site-init

start_xinit () {
	${INIT_DIRECTORY}/obexdstart
	${INIT_DIRECTORY}/displaystats
}

stop_xinit () {
	killall obexpushd
	killall displaystats
}

restart_xinit () {
	stop_xinit
	start_xinit
}

case $1 in
	start) start_xinit ;;
	stop) stop_xinit ;;
	restart|force-reload) restart_xinit ;;
	status) exit 0 ;;
	*) echo "xinit {start|stop|restart}" ;;
esac
